<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        
        <?php if (isset($posts)) : ?>
            <?php foreach($posts as $post): ?>
                <h2><?= $post->title ?></h2>
                <p><?= $post->content ?></p>
                <p>Try <a href="http://slim.local/rate/<?= $post->id ?></p>">like</a></p>
                <hr>
            <?php endforeach; ?>
        <?php endif; ?>

    </body>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
    $.ajax({
        url: "http://slim.local/posts",
        type: 'GET',
        // dataType: 'json', // added data type
        success: function(res) {
            console.log(res);
            // alert(res);
        }
    });
    </script>
</html>
